name: Print Value

on:
  workflow_dispatch:
    inputs:
      value:
        description: 'Select a value to print'
        required: true
        default: 'Dev' # Set 'Dev' as the default value
        options: # Define the options to choose from
          - Dev
          - stg

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print the provided value
        run: echo "The selected value is ${{ github.event.inputs.value }}"
