name: Choose Value

on:
  workflow_dispatch:

jobs:
  choose_value:
    runs-on: ubuntu-latest
    steps:
      - name: Choose value
        id: choose_value
        run: |
          echo "::set-output name=value::$(echo -e "Option 1\nOption 2\nOption 3" | fzf)"
      
      - name: Print chosen value
        run: echo "Chosen value is ${{ steps.choose_value.outputs.value }}"
