name: Print Value

on:
  workflow_dispatch:
    inputs:
      value:
        description: 'Value to print'
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print the provided value
        run: echo "The provided value is ${{ github.event.inputs.value }}"
