name: Print Value

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Print the provided value
        run: echo "The selected env value is s3://${DEV_S3_VALUE}/"
